simulator:
  random_seed: 17
agent:
  height: 1.4
  sensor_specifications:
    - type: RGBA
      resolution: [1024, 1024]
    - type: SEMANTIC
      resolution: [1024, 1024]

  # action_space:
    # move_forward:
      # amount: 3.
tasks:
  - name: "MyTask"
    # type: "VoidTask"
    type: "ObjectNav"
    object_asset: 'sphere'
    max_steps: 1000
    difficulty: 'TRIVIAL'
  - name: "MyTask2"
    type: "VoidTask"
    max_steps: 10

task_iterator:
  max_task_repeat_episodes: 1

scene:
  # dataset_paths: ['data/scene_datasets/habitat-test-scenes/']
  # dataset_paths: ['/home/nick/datasets/habitat/gibson/gibson/']
  scene_path: '/home/nick/datasets/habitat/replicav1/room_2/habitat/mesh_semantic.ply'