simulator:
  random_seed: 7
agent:
  # sensor: ['rgb', 'depth']
  action_space:
    move_forward:
      name: 'some_name'
# tasks:
#   - name: "MyTask"
#     type: "VoidTask"
#     sensors: ['rgb']

scene:
  dataset_paths: ['data/scene_datasets/habitat-test-scenes/']