simulator:
  random_seed: 7
# agent:
  # sensor: ['rgb', 'depth']
# tasks:
#   - name: "MyTask"
#     type: "VoidTask"
#     sensors: ['rgb']

scene:
  dataset_paths: ['data/scene_datasets/habitat-test-scenes/']