simulator:
  random_seed: 77
agent:
  height: 1.4
  sensor_specifications:
    - type: RGBA
      resolution: [1024, 1024]
      position: [0., 0.6, 0.,]
    - type: SEMANTIC
      resolution: [1024, 1024]
      

  # action_space:
    # move_forward:
      # amount: 0.01
    # turn_right:
      # amount: 1
    # turn_left:
      # amount: 1
tasks:
  - name: "MyTask"
    type: "ObjectNav"
    object_asset: '/home/nick/projects/habitat-data/objects/skillet'
    max_steps: 1000
    difficulty: 'TRIVIAL'
  - name: "MyTask2"
    type: "VoidTask"
    max_steps: 1000

task_iterator:
  max_task_repeat_episodes: 1

scene:
  # to test out multiple datasets
  # dataset_paths: ['/home/nick/projects/habitat-data/versioned_data/']
  # max_scene_repeat_episodes: 1
  # cycle_datasets: true
  # to test out single datasets
  scene_path: '/home/nick/projects/habitat-data/scene_datasets/apartment_1.glb'
  # scene_path: '/home/nick/projects/habitat-data/versioned_data/hm3d-1.0/hm3d/example/00337-CFVBbU9Rsyb/CFVBbU9Rsyb.basis.glb'