simulator:
  random_seed: 7
agent:
  height: 1.4
  sensor_specifications:
    - type: RGB
  # action_space:
    # move_forward:
      # name: 'some_name'
tasks:
  - name: "MyTask"
    type: "VoidTask"
    max_steps: 10
    # sensors: ['rgb']

scene:
  dataset_paths: ['data/scene_datasets/habitat-test-scenes/']